name: 🚀 Nouvelle Pull Request
description: Proposez vos modifications pour améliorer Papillon
title: '[PR]: '
labels: [pull-request]
body:
  - type: markdown
    attributes:
      value: |
        Merci de vous référer à la documentation sur la contribution si vous avez des questions à propos des pull requests (https://gitbook.getpapillon.xyz/organisation/outils-internes/github)
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist d'avant pull request
      description: Veuillez cocher toutes les cases applicables.
      options:
        - label: Vous avez testé de build le projet avec vos modifications et ce build **a réussi**
        - label: Vous respectez les conventions de codage et de nommage du projet
        - label: Vous utilisez la **tabulation** pour l'indentation afin de maintenir un code lisible
        - label: Cette pull request **n'est pas un duplicata** d'une autre
        - label: Cette pull request est prête à être **revue** (review) et **fusionnée** (merge)
        - label: Il n'y a pas de **`TODO`** (aka des annotations pour du code manquant) dans vos modifications
        - label: Il n'y a pas **d'erreurs de langue** dans votre code (grammaire, vocabulaire, conjugaison, orthographe)
        - label: Les détails des changements ont été décrits ci-dessous
        - label: Cette pull-request n'est pas une **"breaking-change"** (des modifications qui vont entraîner la modification du fonctionnement de certaines fonctionnalités déjà existantes)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Changelogs proposés
      description: Décrivez les modifications que vous avez effectuées.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Informations supplémentaires
      description: Ajoutez ici toute information supplémentaire si nécessaire.
    validations:
      required: false
