name: Checks (TypeScript + ESLint)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: 🛠️ TypeScript and ESLint
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: ⚙️ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: 💾 Install dependencies
        run: npm install

      - name: 🔍 Run TypeScript and ESLint checks
        id: lint
        run: |
          npm run lint > lint.log 2>&1 || echo "Lint failed" >> lint.log
        continue-on-error: true

      - name: Set lint result
        id: lint_result
        run: |
          if grep -q "Lint failed" lint.log; then
            echo "LINT_FAILED=true" >> $GITHUB_ENV
          else
            echo "LINT_FAILED=false" >> $GITHUB_ENV

      - name: 📂 Post logs on failure
        if: env.LINT_FAILED == 'true'
        run: |
          echo "### :x: TypeScript and ESLint checks failed!" >> comment.txt
          echo '```' >> comment.txt
          cat lint.log >> comment.txt
          echo '```' >> comment.txt

      - name: 👁️‍🗨️ Comment on Pull Request
        if: env.LINT_FAILED == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ⚠️ Erreur(s) détectée(s) par TypeScript/ESLint !
          message: |
            :x: Voici les détails :

            file://comment.txt

      - name: 🧹 Clean up
        if: always()
        run: rm -f lint.log comment.txt
